name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.8.1"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test

  version:
    name: Version
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.8.1"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Determine version
        id: version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run semantic-release to update version
          npx semantic-release
          # Get the new version
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: [test, version]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.8.1"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build
          path: dist/
          
  release:
    name: Release
    needs: [test, version, build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.8.1"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: electron-build
          path: dist/

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create release notes from git log if CHANGELOG.md doesn't exist
          if [ ! -f CHANGELOG.md ]; then
            echo "## What's Changed" > CHANGELOG.md
            git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" >> CHANGELOG.md
          fi
          
          # Upload AppImage if it exists
          if ls dist/*.AppImage 1> /dev/null 2>&1; then
            gh release upload "v${{ needs.version.outputs.version }}" dist/*.AppImage --clobber
          fi
          
          # Upload deb package if it exists
          if ls dist/*.deb 1> /dev/null 2>&1; then
            gh release upload "v${{ needs.version.outputs.version }}" dist/*.deb --clobber
          fi 